backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "character"
    label: "Character"
    folder: "src/pages/character"
    create: true
    slug: "{{slug}}"
    fields:

      - { label: "Name", name: "title", widget: "string" }
      - { label: "Manga debut", name: "debut", widget: "string" }
      - { label: "Faction", name: "faction", widget: "select", options: ['Kakin', 'Bodyguards', 'Zodiacs'] }
      - { label: "Img path", name: "img", widget: "hidden" }
      - { label: "Template key", , name: "templateKey", widget: "hidden", default: "new-character"}
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
